import Head from 'next/head'
import Link from "next/link";

export default function FirstPost() {
  return (
    <div>
      <Head>
        <title>最初の投稿</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>最初の投稿</h1>
      <Link href="/">ホームへ戻る</Link>
    </div>
  );
}
